""""""""""""""""""""""""""""
" mintyfwesh minimal vimrc "
""""""""""""""""""""""""""""

"" Plugins
""""""""""
call plug#begin('~/.vim/plugged')
Plug 'editorconfig/editorconfig-vim'
call plug#end()

"" Aliases
""""""""""
" Fast go to buffer x.
"nnoremap gb :ls<CR>:b<Space>

" Default tab behavior
" Explanation of tab settings:
" - tabstop (ts) - Default width of an actual TAB
" - shiftwidth (sw) - Width of an indent level
" - softtabstop (sts) - Width/columns of a TAB (whether tabs or spaces)
"                       Makes backspace delete (sts) number of spaces at once
" - expandtab (et) - Pressing TAB inserts spaces
" - noexpandtab (noet) - Pressing TAB inserts actual tab
" - smarttab - Pressing TAB indents to the next tabstop when at the
"              beginning of a line
set tabstop=4 shiftwidth=4 softtabstop=4 expandtab smarttab
set autoindent

"" Autocommands
"""""""""""""""
"if has("autocmd")
	" au = autocmd, setl = setlocal, ft = filetype

	" Use filetype detection and file-based automatic indenting.
	"filetype plugin indent on

	" Turn off automatic insertion of comments upon new line.
	"autocmd FileType * setl formatoptions-=c formatoptions-=r formatoptions-=o

	" Use tab/space behavior based on filetype.
	"autocmd FileType make setl noexpandtab

	"autocmd FileType javascript,json setl ts=2 sw=2 sts=2 et
	"autocmd FileType html setl ts=2 sw=2 sts=2 et
	"autocmd FileType css,scss,sass setl ts=2 sw=2 sts=2 et
    "autocmd FileType markdown setl ts=2 sw=2 sts=2 et

	"autocmd FileType python setl ts=4 sw=4 sts=4 et
	"autocmd FileType cpp setl ts=2 sw=2 sts=2 et

	" Syntax highlighting for special files.
	"autocmd BufRead,BufNewFile *.handlebars,*.hbs set ft=html
"endif

"" Appearance
"""""""""""""
colorscheme desert

syntax enable       " Syntax highlighting (previously syntax on).

set number          " Line numbers.
set laststatus=2    " Status line/bar on 2nd to last line.
set wildmenu        " Shows command completions in status line.
"set ruler           " Show info in status line.
"set nowrap          " Don't wrap text.
set showcmd         " Show keystrokes for each command.
"set showmode
set colorcolumn=81  " Highlights column 81, etc.
set display+=lastline " Display as much of the last line as possible
                      "   instead of @.

"" Netrw Directory Explorer
" Use :e. or :edit . to open in current window (recommended)
" Use :Vex command to open in split

"" Behavior
"""""""""""
"if has("clipboard")
"    set clipboard=unnamed " Copy to system clipboard (if supported)
"endif

" Save swap files in a specific directory (rather than the current one)
"set directory=~/.vim/swapfiles//

"set nobomb          " Don't allow byte-order marks (invisible char).
"set fileformat=unix  " Set fileformat to unix-style line endings.
"set fileformats=unix,mac,dos  " Specify which fileformats to check when opening
                    "   files. The first ffs is also the one used for new buffers.
"set splitbelow      " Open new splits below.
"set splitright      " Open new splits to the right.
set visualbell      " Blink cursor on error.
set noerrorbells    " Turn off bell sound.
set backspace=2     " Deletes indent, eol, start.
"set nohidden        " Buffers will be actually closed and not hidden.
"set formatoptions=cqrt  "Newline will continue comments.
"set whichwrap=<,>,h,l  " Left, right can move cursor onto next line instead of
                    "   stopping.
"set nostartofline   " Cursor stays in the same column when running commands like
                    "   gg.
"set textwidth=80    " Break up lines longer than 80 chars when typing.

"" Search
"""""""""
set hlsearch            " Turn on search highlighting
                        "   To clear highlighting, use :nohightlight or :noh
"set nohlsearch          " Turns off search highlighting completely.
"set ignorecase          " Make searches case-insensitive.
                        "   To perform case insensitive search: use \c anywhere
                        "   in the search string.
                        "   e.g. /Copyright\c will be case insensitive
"set smartcase           " Case sensitive searches triggered only by capital
                        "   letters in search term. (ignorecase must be set)
" Change search highlighting (default can be hard to read).
"highlight Search ctermfg=3 ctermbg=0

"" Statusline
"""""""""""""
" For more info, see :help statusline
set statusline=(%n)\        " Buffer number
set statusline+=%f\         " Filename
set statusline+=%m          " Modified flag
set statusline+=%=          " Left/right separator
set statusline+=%r\         " Readonly flag
set statusline+=%y\         " Filetype
set statusline+=[%{&ff}]\   " File format (line ending style)
set statusline+=%c,\        " Current column
set statusline+=%l/%L\      " Current/total line
